### ISSUE TITLE
Is a mega PR welcome?

### ISSUE THREAD

**Issue by diondokter** [braun-embedded/rust-dw1000#133]
Hi!

So, the title says a lot.
I've done work on this library up until about half a year ago.
I was going to upstream it in nice chunks, at least that was the idea.
But now the project has been cancelled and I'm putting all my free time in renovating my house.
It's a waste though to let all these nice features go to waste in an unmaintained fork.

https://github.com/diondokter/rust-dw1000

Things that have been added:

- Double buffering RX
- RSSI and LOS calculations
- Sleep and wakeup
- Range bias calculations
- External sync modes (for TDOA systems)
- HL split up into multiple files (one for each state) because it got way too big
- Probably more small things that I don't really remember

It all did work though... All of these were used successfully in my project before it was cancelled.

I don't want to burden you with this, so I'll leave it up to you.
Do you want me to make the PR? Apparently there will be no merge conflicts, so it is up-to-date enough with the current master I think.

**Comment by hannobraun** [comment]
Hey @diondokter, thanks for opening this issue. Let's do it! I'm not actively developing this crate, except for routine maintenance, and I'm not aware of any other work that might conflict with yours. As you say, it would be a waste not to upstream your improvements.

I haven't taken a look at your changes yet. It's possible that it's more than I can review in a reasonable time frame, but since you're a known member of the Embedded Rust community (and previous contributor to this project!), I feel comfortable to just trust you and cut corners in review as necessary.
